spring.application.name=Enterprise

server.servlet.context-path=/api
server.port=8092

spring.data.mongodb.uri=mongodb://localhost:27017/enterprise

enterprise.app.jwtSecret=hjlkjhhhhikmhstvlyigkf;fidrfgvhgfhgfjkhkhjfdfffffffghgfjhjuhgjuty
enterprise.app.jwtExpirationMs=86400000
enterprise.app.jwtRefreshExpirationMs=432000000
app.frontend.url=http://localhost:5173